### ISSUE TITLE
tutorial 1 begins with a file not in this repo

### ISSUE THREAD

**Issue by raynamharris** [juanbot/CoExpNets#17]
I would like to try your tutorials, but [tutorial 1](https://github.com/juanbot/CoExpNets/blob/master/inst/tutorials/Tutorial_1.md) begins with a file not in this repo. 

```
expr.data  = readRDS("~/tmp/rosmap_residuals.rds")
```

How are we supposed to follow along if we can't even execute line 1 of the tutorial? Can you please add this file or include the code to generate this "tmp" file?

**Comment by Rosenine** [comment]
I got the same issue, please resolve this.
